---
# This file contains all available package-ecosystems.
# Just uncomment the ones you use in your repo.
# You can also change the path to be more specific.
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
#  - package-ecosystem: "bundler"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "cargo"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "composer"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "mix"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "elm"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "gitsubmodule"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "gomod"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "gradle"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "maven"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "nuget"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "pip"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "pub"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "swift"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#  - package-ecosystem: "terraform"
#    directory: "/"
#    schedule:
#      interval: "weekly"