name: run-tests
on:
  pull_request:

  push:
    branches:
      main
jobs:
  sast:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SAST.yml@main
  secret-detection:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SecretDetection.yml@main
  python-linting:
    uses: SmartDCSITlimited/actions-store/.github/workflows/PythonLinting.yml@main
